version: '3.7'
x-images:
  bypass: &bypass
    command: echo "not started"
    restart: "no"
    entrypoint: echo "not started"
services:
  backup: {<<: [ *bypass ]}
  nginx: {<<: [ *bypass ]}
  backup: {<<: [ *bypass ]}
  {{cookiecutter.app_type}}:
    environment:
      - DJANGO_SETTINGS_MODULE=${{{cookiecutter.app_type.upper()}}_SETTINGS_MODULE:-project.settings.dev}
      - NO_MIGRATE=1
      - NO_COLLECT_STATIC=1
      - NO_GUNICORN=1
    command: "gosu {{cookiecutter.app_type}} ../start.sh"
    volumes:
      - ./local/terra-back-deploy/prod/sudoer:/etc/sudoers.d/{{cookiecutter.app_type}}
      - ./lib:/code/lib
      - ./local:/code/local
      - ./src:/code/src
      - ./private:/code/private
      - ./tox.ini:/code/tox.ini
      - ./local/terra-back-deploy/prod/init.sh:/code/init.sh
      - ./local/terra-back-deploy/prod/start.sh:/code/start.sh
      - ./.tox:/code/.tox
      - ./requirements.txt:/code/requirements.txt
      - ./requirements-dev.txt:/code/requirements-dev.txt
    ports:
      - "8000:8000"
