version: '3.7'
x-images:
  env: &env {env_file: [.env, docker.env]}
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    <<: [ *env ]
    tty: true
    image: "${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE}:${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE_VERSION}"
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-project.settings.prod}
    depends_on:
      - db
      - redis
    working_dir: /code/src
    command: /bin/bash /code/init/init.sh
    volumes:
      - mediafiles:/code/public/media
      - statics:/code/public/static
      - logs:/logs/
services:
  mailcatcher:
    <<: [ *env ]
    image: djfarrelly/maildev
    hostname: mailcatcher
    entrypoint: "./bin/maildev --web 80 --smtp 25 --base-pathname '/mailcatcher/'"
  redis:
    <<: [ *env ]
    image: redis:4.0-alpine
    hostname: redis
    volumes:
      - 'redis:/data'
  db:
    <<: [ *env ]
    image: makinacorpus/pgrouting:10.1-2.5.4
    volumes:
      - postgresql:/var/lib/postgresql/data
  nginx:
    <<: [ *env ]
    restart: always
    image: nginx:1.14-alpine
    depends_on:
      - {{cookiecutter.app_type}}
    volumes:
      - ./local/terra-back-deploy/prod/etc/nginx/vhost.conf.template:/etc/nginx/conf.d/vhost.conf.template
      - mediafiles:/public/media/:ro
      - statics:/public/static/
      - logs:/logs/
    command: >
      /bin/sh -c
      "envsubst '
      $$FRONT_URL
      '< /etc/nginx/conf.d/vhost.conf.template
      > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"
      # Replace hostname in vhost.conf
  {{cookiecutter.app_type}}:
    <<: [ *{{cookiecutter.app_type}} ]
  cron:
    <<: [ *{{cookiecutter.app_type}} ]
    depends_on:
      - {{cookiecutter.app_type}}
    command: /bin/sh /code/cron.sh
  backup:
    <<: [ *env ]
    image: "corpusops/dbsmartbackup:pg10"
    restart: always
    volumes:
      - backupdb-dumps:/srv/backups/
      - backupdb-logs:/srv/backups/logs/
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./local/backup/setup/reconfigure.yml:/setup/reconfigure.yml:ro
  convertit:
    <<: [ *env ]
    image: makinacorpus/convertit
    hostname: convertit
volumes:
  backupdb-logs:
  backupdb-dumps:
  postgresql:
  redis:
  mediafiles:
  statics:
    name: "${{'{'}}{{cookiecutter.app_type.upper()}}_NAME}back-statics-${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE_VERSION}"
    external: false
  logs:
