version: '3.7'
x-django: &django
  volumes:
  - ./local.py:/code/src/project/settings/local.py
  environment:
  - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-project.settings.prod}
services:
  nginx:
    ports:
    - 80:80
  cron:
    <<: [ *django ]
  django:
    <<: [ *django ]
    ports:
    - "8000:8000"
