version: '3.7'
x-images:
  bypass: &bypass
    command: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
    entrypoint: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
    restart: "no"
services:
  backup: {<<: [ *bypass ]}
  nginx:
    environment:
    - NO_SSL=
    - NO_STATICS=''
    ports:
    - "80:80"
    - "443:443"
  backup: {<<: [ *bypass ]}
  {{cookiecutter.app_type}}:
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-project.settings.dev}
      - NO_MIGRATE=1
      - NO_COLLECT_STATIC=1
      - NO_GUNICORN=1
    volumes:
      - ./local/terra-back-deploy/prod/sudoer:/etc/sudoers.d/$APP_TYPE
      - ./local/terra-back-deploy/prod/init.sh:/code/init/init.sh
      - ./local/terra-back-deploy/prod/start.sh:/code/init/start.sh
      - ./local/terra-back-deploy/prod/cron.sh:/code/init/cron.sh
      - ./lib:/code/lib
      - ./local:/code/local
      - ./src:/code/src
      - ./private:/code/private
      - ./tox.ini:/code/tox.ini
      - ./.tox:/code/.tox
      - ./requirements.txt:/code/requirements.txt
      - ./requirements-dev.txt:/code/requirements-dev.txt
    ports:
      - "8000:8000"
