version: '3.7'
x-images:
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    build: {context: "."}
services:
  cron: {<<: [ *{{cookiecutter.app_type}} ]}
  {{cookiecutter.app_type}}: {<<: [ *{{cookiecutter.app_type}} ]}
