---
terralegoback_servers: terralegoback_servers
cops_terralego_name: "{{cookiecutter.lname}}"
cops_terralego_tld_domain: "{{cookiecutter.tld_domain}}"
cops_terralego_mail_domain: "{{ cookiecutter.mail_domain }}"
cops_terralego_docker_image: "{{cookiecutter.docker_image}}"
cops_terralego_gitref: "{{'{{'}}lookup('env', 'CI_COMMIT_TAG_NAME') or lookup('env', 'CI_COMMIT_REF_NAME') or 'latest'}}"
cops_terralego_docker_tag: "{{'{{'}}cops_terralego_gitref}}"
