---
terralegoback_servers: terralegoback_servers
cops_terralego_name: "{{cookiecutter.lname}}"
cops_terralego_tld_domain: "{{cookiecutter.tld_domain}}"
cops_terralego_mail_domain: "{{ cookiecutter.mail_domain }}"
cops_terralego_docker_image: "{{cookiecutter.docker_image}}"
cops_terralego_gitref: "{{'{{'}}lookup('env', 'CI_COMMIT_TAG_NAME') or lookup('env', 'CI_COMMIT_REF_NAME') or 'latest'}}"
cops_terralego_docker_tag: "{{'{{'}}cops_terralego_gitref.replace('master', 'latest')}}"

cops_terralego_gunicorn_class: "{{cookiecutter.gunicorn_class}}"

cops_terralego_postgres_startup_timeout: 45s
cops_terralego_docker_env_extra: |-
  POSTGRES_STARTUP_TIMEOUT={{'{{'}}cops_terralego_postgres_startup_timeout}}
